fix: ci pipeline

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -29,4 +29,4 @@ jobs:
         if: failure()
         run: |
           echo "⚠️ Tests failed. Blocking merge to the branch."
-          exit 1
+          exit 1  # Exit with a non-zero status code to fail the jo
